version: "3.9"
services:
  irs_react:
    container_name: irs_react
    image: reidwarner/irs_react:latest
    ports:
      - 5173:5173
  irs_flask_api:
    container_name: irs_flask_api
    image: reidwarner/irs_flask_api:latest
    ports:
      - 5000:5000
    networks:
      - irsnet
    environment:
      - DB_URL=postgresql://postgres:postgres@irsdb:5432/postgres
    depends_on:
      irsdb:
        condition: service_healthy
  irsdb:
    container_name: irsdb
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - irsnet
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  pgdata: {}
networks:
  irsnet:
    driver: bridge

